name: Deploy Frontend
on:
  push:
    branches:
      - main 

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_REGION: 'us-east-1'
  APPLICATION_NAME: 'docker'
  ENVIRONMENT_NAME: 'Docker-env'
  BUCKET_NAME: 'elasticbeanstalk-us-east-1-847555796967'
  IMAGE_TAG: 'xkrb/docker'
  DOCKERFILE_DEV_PATH: 'Dockerfile.dev'
  
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u "${{ env.DOCKER_USERNAME }}" -p "${{ env.DOCKER_PASSWORD }}"
      - run: docker build -t "${{ env.IMAGE_TAG }}" -f "${{ env.DOCKERFILE_DEV_PATH }}" .
      - run: docker run -e CI=true "${{ env.IMAGE_TAG }}" npm run test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
 
 #     - name: Deploy to EB
 #       uses: einaregilsson/beanstalk-deploy@v18
  #      with:
   #       aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
   #       aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
    #      application_name: docker
     #     environment_name: Docker-env
      #    existing_bucket_name: elasticbeanstalk-us-east-1-847555796967
       #   region: us-east-1
        #  version_label: ${{ github.sha }}
         # deployment_package: deploy.zip
      