name: Deploy Frontend
on:
  push:
    branches:
      - main 
  
jobs: 
  build:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t xkrb/docker -f Dockerfile.dev .
      - run: docker run -e CI=true xkrb/docker npm run test
      
      