name: Deploy Frontend
on:
  push:
    branches:
      - main 
  
jobs: 
  build:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.AWS_ACCESS_KEY }} -p ${{ secrets.AWS_SECRET_KEY }}
      - run: docker build -t xkrb/docker -f Dockerfile.dev .
      - run: docker run -e CI=true xkrb/docker npm test
      
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          application_name: docker
          environment_name: Docker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-847555796967
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
